name = "Waveguides_FrFT"
uuid = "18708e35-cfd0-436f-9746-59582cfdf0b3"
authors = ["Alejandro R. Urzúa <arurz@inaoep.mx>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialMatrices = "928aab9d-ef52-54ac-8ca1-acd7ca42c160"

[compat]
julia = "1.5"
